spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: 10.99.100.217:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 16384  # 16KB - размер батча
      linger-ms: 5  # Накопление сообщений для батча
      buffer-memory: 33554432  # 32MB буфер
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="hOKPRLqhHH";

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
      base-path: /actuator  # ?? ?????????, ?? ????? ??????? ????
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true