spring:
  application:
    name: producer
  kafka:
    bootstrap-servers: 10.99.100.217:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 16384  # 16KB - размер батча
      linger-ms: 5  # Накопление сообщений для батча
      buffer-memory: 134217728  # 128MB буфер
      max-block-ms: 60000        # 60 секунд ожидания при заполнении буфера
    properties:
      delivery.timeout.ms: 120000  # 2 минуты на всю доставку
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="hOKPRLqhHH";

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
      base-path: /actuator  # ?? ?????????, ?? ????? ??????? ????
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true