spring:
  application:
    name: producer
  kafka:
    # ????? ?????? Kafka-??????? ?????? ???????? Kubernetes
    bootstrap-servers: 10.99.100.217:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      # ?????????, ??? ????? ???????????? SASL ??? ?????????? (SASL_PLAINTEXT)
      security.protocol: SASL_PLAINTEXT
      # ????????? ???????? SASL. ? ????? ?????? ??? PLAIN [citation:5][citation:10]
      sasl.mechanism: PLAIN
      # ????????????? JAAS-???????????? ? ?????? ???????????? ? ???????
      # ?????: ???????? your-username ? your-password ?? ???????? ???????? ?? ?????? ??????? Kubernetes
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="hOKPRLqhHH";

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
      base-path: /actuator  # ?? ?????????, ?? ????? ??????? ????
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true