spring:
  application:
    name: kafka-consumer-demo
  kafka:
    # ????? ?????? Kafka-??????? (?????? ????????? ? ??????????)
    bootstrap-servers: 10.99.100.217:9092
    consumer:
      group-id: my-consumer-group  # ?????? ??? offset management
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ????????? ????-?????? offset'?? (?????? ??????????)
      enable-auto-commit: false
      # ???????? ?????? ? ?????????? ????????? (latest) ??? ? ?????? (earliest)
      auto-offset-reset: earliest
      max-poll-records: 10  # ???????? ????????? ?? ???? ??????
    listener:
      # ?????? ????????????? (acknowledgment) ??? ???????? ?????????
      ack-mode: manual_immediate
    properties:
      # SASL ?????????????? (?? ?? ?????????, ??? ? ? ?????????)
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="user1" password="hOKPRLqhHH";

# ??????????? ??? ???????
logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
      base-path: /actuator  # ?? ?????????, ?? ????? ??????? ????
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true