## my-values.yaml
## Включаем режим KRaft
kraft:
  enabled: true

# Настройка контроллеров (у вас уже есть, но можно явно указать)
controller:
  replicaCount: 3
  controllerOnly: true # Указывает, что эти поды будут только контроллерами

# НАСТРОЙКА БРОКЕРОВ
broker:
  replicaCount: 4      # Добавляем 3 брокера
  persistence:
    size: 10Gi         # Размер диска для данных

# АВТОМАТИЧЕСКОЕ СОЗДАНИЕ ТОПИКОВ (provisioning)
provisioning:
  enabled: true
#  numPartitions: 12     # Количество партиций по умолчанию для новых топиков
  replicationFactor: 3 # Фактор репликации (должен быть <= кол-ва брокеров)
  topics:
    # Список топиков, которые будут созданы автоматически
    - name: "test-topic"
      partitions: 12
      replicationFactor: 3
      config:
        retention.ms: "86400000" # Хранить сообщения 1 день (в миллисекундах)
        max.message.bytes: "10485760" # Макс. размер сообщения 10MB
    - name: "my-app-logs"
      partitions: 5
      replicationFactor: 3
      config:
        retention.bytes: "1073741824" # Хранить до 1GB
common:
  resources:
    preset: "large"
listeners:
  client:
    protocol: SASL_PLAINTEXT
    containerPort: 9092
    name: CLIENT
  controller:
    protocol: PLAINTEXT
    containerPort: 9093
    name: CONTROLLER
  interbroker:
    protocol: PLAINTEXT
    containerPort: 9094
    name: INTERNAL
sasl:
  client:
    users:
      - user
    passwords:
      - test
# Настройка для доступа из клиентов (ваших Spring Boot приложений) внутри кластера
service:
  type: ClusterIP
  ports:
    client: 9092