apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: "{{ .Values.docker.repository }}/{{ .Values.demo.image.name }}:{{ .Values.demo.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "demo-postgresql.default.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-postgresql
                  key: postgres-password