{{/*{{- if .Values.prometheusOperator.enabled | default false }}*/}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-producer-monitor
  namespace: default  # <-- ДОБАВИТЬ, если Prometheus в default namespace
  labels:
    # Важно: эти метки должны совпадать с prometheus.prometheusSpec.serviceMonitorSelector в kube-prometheus-stack
    release: kube-prometheus-stack  # Обычно по умолчанию
    app: kube-prometheus-stack-prometheus
spec:
  selector:
    matchLabels:
      monitoring: "true"  # Ищем Service с этой меткой
  namespaceSelector:
    matchNames:
     - default
  endpoints:
    - port: metrics-port  # Используем имя порта из Service
      scheme: http
      path: /actuator/prometheus  # Spring Boot default path
      interval: 30s
      scrapeTimeout: 10s
{{/*{{- end }}*/}}