apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.demo.image.name }}-service
  namespace: default
  labels:
    monitoring: "true"  # <-- Критически важно для ServiceMonitor
spec:
  selector:
    app: {{ .Values.demo.image.name }}
  ports:
    - name: metrics-port  # <-- Имя порта должно совпадать с ServiceMonitor
      protocol: TCP
      port: 8080
      targetPort: 8080